
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: pass
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect